# Generated by Django 5.1.7 on 2025-04-03 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_course_exam_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="exam_duration",
        ),
        migrations.AddField(
            model_name="course",
            name="exam_end_time",
            field=models.TimeField(
                default=datetime.time(10, 30),
                help_text="Enter exam end time in HH:MM:SS format",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="exam_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Enter exam start time in HH:MM:SS format",
            ),
        ),
    ]
