# Generated by Django 5.1.7 on 2025-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="syllabus",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="syllabus",
            name="session",
            field=models.CharField(
                choices=[("FN", "Forenoon"), ("AN", "Afternoon")],
                default="FN",
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syllabus",
            unique_together={("clg", "day", "session")},
        ),
    ]
