# Generated by Django 5.1.7 on 2025-03-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_group",
                    models.CharField(
                        choices=[
                            ("Aptitude & Reasoning", "Aptitude & Reasoning"),
                            (
                                "Communication & Soft Skill",
                                "Communication & Soft Skill",
                            ),
                            ("Aptitude & Soft Skill", "Aptitude & Soft Skill"),
                            ("Technical", "Technical"),
                        ],
                        default="Aptitude",
                        max_length=50,
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("question_number", models.PositiveIntegerField()),
                ("total_marks", models.PositiveIntegerField()),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.PositiveIntegerField()),
                ("question", models.CharField(max_length=600)),
                ("option1", models.CharField(max_length=200)),
                ("option2", models.CharField(max_length=200)),
                ("option3", models.CharField(max_length=200)),
                ("option4", models.CharField(max_length=200)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("Option1", "Option1"),
                            ("Option2", "Option2"),
                            ("Option3", "Option3"),
                            ("Option4", "Option4"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="No explanation provided.", null=True
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
