# Generated by Django 5.1.7 on 2025-03-30 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sources",
            name="course_name",
            field=models.CharField(
                choices=[
                    ("Aptitude & Reasoning", "Aptitude & Reasoning"),
                    ("Communication & Soft Skill", "Communication & Soft Skill"),
                    ("Aptitude & Soft Skill", "Aptitude & Soft Skill"),
                    ("Technical", "Technical"),
                ],
                default="Aptitude & Reasoning",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/notes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "png", "jpg"]
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("class", "Class Notes"),
                            ("test", "Test Notes"),
                            ("infographic", "Infographic Notes"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "subtitle_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.sources"
                    ),
                ),
            ],
        ),
    ]
