# Generated by Django 5.1.7 on 2025-04-03 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="exam_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=1500),
                help_text="Enter duration in HH:MM:SS format",
            ),
        ),
    ]
