# Generated by Django 5.1.7 on 2025-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0003_remove_course_exam_duration_course_exam_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="priority",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
